name: test
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: maxxing/compiler-dev
    steps:
      - uses: actions/checkout@v2
        with:
          path: /root
        name: run autotest
        run: autotest --koopa -s lv1 /root/SysYCompiler


