name: test
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: maxxing/compiler-dev
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: list dir
        run: ls  
      - name: run autotest
        run: autotest -koopa -s lv1 SysYCompiler


