name: test
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: maxxing/compiler-dev
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: rust toolchains
        run: rustup install stable
      - name: cp to root
        run: cp -r ../SysYCompiler /root
      - name: run autotest
        run: autotest -koopa -s lv1 /root/SysYCompiler


