name: test
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: maxxing/compiler-dev
    steps:
      - name: checkout code
        uses: actions/checkout@v2
          # - name: remove the tuna source
          #run: rm /root/.cargo/config
      - name: move config to .cargo
        run: mv ./config /root/.cargo
      - name: cp to root
        run: cp -r ../SysYCompiler /root
      - name: change the env
        run: |
          unset -v RUSTUP_UPDATE_ROOT
          unset -v DIST_SERVER
      - name: set default toochains
        run: |
          rustup install stable
          rustup update stable
      - name: cargo new
        run: |
          /root/.cargo/bin/cargo new --bin test
          #          rustup install stable
          #          #      - name: run autotest
          #          #        run: autotest -koopa -s lv1 /root/SysYCompiler
          #          rustc --version

